### ISSUE TITLE
Add citations to your paper

### ISSUE THREAD

**Issue by zhujiem** [SkylerLinn/Understanding-the-Ranking-Loss#1]
Please cite the following two papers in your paper for FuxiCTR and BARS. I found you missed them.

Jieming Zhu, Jinyang Liu, Shuai Yang, Qi Zhang, Xiuqiang He. [Open Benchmarking for Click-Through Rate Prediction](https://arxiv.org/abs/2009.05794). The 30th ACM International Conference on Information and Knowledge Management (CIKM), 2021.

Jieming Zhu, Quanyu Dai, Liangcai Su, Rong Ma, Jinyang Liu, Guohao Cai, Xi Xiao, Rui Zhang. [BARS: Towards Open Benchmarking for Recommender Systems](https://arxiv.org/abs/2009.05794). The 45th International ACM SIGIR Conference on Research and Development in Information Retrieval (SIGIR), 2022.

**Comment by SkylerLinn** [comment]
Thanks for your reminding, we will cite these mentioned papers in next version of our paper.

**Comment by zhujiem** [comment]
Thanks! Please also refine the URLs since the links have been moved to new repos. 
https://github.com/reczoo/FuxiCTR
https://github.com/reczoo/BARS

**Comment by zhujiem** [comment]
Please update footnotes ULRs to these:
1. https://github.com/reczoo/Datasets/tree/main/Criteo/Criteo_x1
2. https://github.com/reczoo/FuxiCTR/tree/main/model_zoo/DCNv2
3. https://github.com/reczoo/BARS/tree/main/ranking/ctr/DCNv2/DCNv2_criteo_x1
