### ISSUE TITLE
如果一个batchsize的样本全为正样本和负样本如何计算pairwise_loss？

### ISSUE THREAD

**Issue by mathlf2015** [SkylerLinn/Understanding-the-Ranking-Loss#2]
请教个问题， 这种情况下 pariwise_loss 是默认为0吗

**Comment by SkylerLinn** [comment]
是的，默认为0

**Comment by mathlf2015** [comment]
> 是的，默认为0

你们这个combine_pair loss对多目标有效没, 还是说只用于单目标的ctr 建模

**Comment by SkylerLinn** [comment]
我们这个研究主要聚焦在单目标优化中应用ranking loss；但在多任务中只要任务间的关系明确，依然是很容易拓展到多任务中的
