### ISSUE TITLE
pair的生成是in-batch吗

### ISSUE THREAD

**Issue by hantaozi** [SkylerLinn/Understanding-the-Ranking-Loss#3]
你好，pair的生成不是基于session或是基于user做聚合的吗，是在batch内不同的label进行组合的？

**Comment by SkylerLinn** [comment]
是基于batch来组合的

**Comment by hantaozi** [comment]
谢谢回复. 前面介绍的Twitter的工作还有JRC应该都是根据session或是造的假pair的吧. 居然基于batch也是有效的。

**Comment by SkylerLinn** [comment]
是的。从我们的视角看，随机的正负样本对(比如同batch内)就可以work，不依赖session
